repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: uv run ruff check --fix
        language: system
        types: [python]
        pass_filenames: true
      - id: pylint
        name: pylint
        entry: uv run pylint
        language: system
        types: [python]
        args:
          [
            "-rn",
            "-sn",
            "--rcfile=.pylintrc",
            "--load-plugins=pylint.extensions.docparams",
          ]
      - id: uv-lock
        name: uv-lock
        entry: bash -c 'uv lock; git add uv.lock'
        language: system
        pass_filenames: false
        stages: [pre-commit]